# Generated by Django 3.1.1 on 2021-08-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_stairs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stairs',
            new_name='Stair',
        ),
    ]
