# Generated by Django 3.1.1 on 2021-08-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_contacts_ourprojects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='OurProjects',
            new_name='OurProject',
        ),
        migrations.RenameModel(
            old_name='PavingSlabs',
            new_name='PavingSlab',
        ),
    ]
