# Generated by Django 3.1.1 on 2021-08-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pavingslab',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stair',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='price',
        ),
        migrations.AddField(
            model_name='pavingslab',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена до'),
        ),
        migrations.AddField(
            model_name='pavingslab',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена от'),
        ),
        migrations.AddField(
            model_name='stair',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена до'),
        ),
        migrations.AddField(
            model_name='stair',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена от'),
        ),
        migrations.AddField(
            model_name='tile',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена до'),
        ),
        migrations.AddField(
            model_name='tile',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена от'),
        ),
    ]
